### ISSUE TITLE
[Refactor] 새로운 버전 API 대응

### ISSUE THREAD

**Issue by L-j-h-c** [sopt-makers/SOPT-iOS#144]
## 📝  To-do

- [x] 레거시 파일 삭제
- [x] 레거시 API 삭제
- [ ] 변경 API 대응
