### ISSUE TITLE
[Chore] 플그 미등록 + 비활동 유저 토큰 관리, 리프레시 로직 수정, 크루팀 URL 변경

### ISSUE THREAD

**Issue by L-j-h-c** [sopt-makers/SOPT-iOS#197]
## 📌  Issue

플그 미등록 + 비활동 유저 토큰 관리, 리프레시 로직 수정, 크루팀 URL 변경

## 📝  To-do

- [ ] 플그 미등록 + 비활동 유저 토큰 관리
- [ ] 리프레시 로직 수정
- [ ] 크루팀 URL 변경
