### ISSUE TITLE
[Feat] FCM 세팅

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-iOS#246]
## 📌  Issue

- 푸시 알림을 위해 FCM 세팅

## 📝  To-do

- [ ] 푸시 알림 인증서 등록
- [ ] Tuist에서 관련 세팅
- [ ] 푸시 알림이 정상적으로 오는지 확인
