### ISSUE TITLE
[Feat] 푸시 알림 관련 서버 연결

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-iOS#257]
## 📌  Issue

- 푸시 알림 관련된 서버 연결을 진행합니다. (마이페이지 부분 제외)

## 📝  To-do

- [x] 기기 토큰 등록 API
- [ ] 알림 리스트 조회 API
- [ ] 알림 읽음 처리 API
- [ ] 메인뷰 API에 알림 유무 필드 추가
