### ISSUE TITLE
[Feat] 알림 수신 스펙 변경 적용

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-iOS#296]
## 📌  Issue

- 푸시 알림 관련 스펙 변경된 사항들을 적용합니다.

## 📝  To-do

- [ ] 알림 리스트뷰 변경
- [ ] 마이페이지 알림 스위치 UI 변경
- [ ] 변경된 API 명세에 맞게 코드 수정
