### ISSUE TITLE
[Feat] ListDetailVC 네비바 분기처리, custom alert 구현

### ISSUE THREAD

**Issue by yangsubinn** [sopt-makers/SOPT-iOS#31]
## 📌  Issue

ListDetailVC 추가 분기처리 및 custom Alert 구현

## 📝  To-do

- [x] 로티 추가
- [x] bottomButton 액션 처리
- [x] 네비바 rightButton 삭제 액션 처리
- [x] 네비바 leftButton 분기처리
- [x] custom alert 
- [x] custom alert 생성해주는 함수 
- [x] input, output 수정
- [x] 하단 버튼 미션 레벨별 분기처리
