### ISSUE TITLE
[Feat] 솝마디 결과 뷰 API 연결

### ISSUE THREAD

**Issue by dlwogus0128** [sopt-makers/SOPT-iOS#386]
## 📌  Issue

솝마디 결과 뷰의 기능 구현 및 API 연결을 합니다. 

## 📝  To-do

- [x] 오늘의 운세 카드 조회 API 연결
- [x] 친구 추천 API 연결
- [x] 콕찌르기 API 연결
- [x] 솝마디 결과 뷰 기능 구현
