### ISSUE TITLE
[Feat] 솝마디 결과 뷰, 부적 화면 전환 및 데이터 바인딩

### ISSUE THREAD

**Issue by dlwogus0128** [sopt-makers/SOPT-iOS#392]
## 📌  Issue

- 솝마디 결과 뷰, 부적 화면 전환
- 부적 화면 데이터 바인딩

## 📝  To-do

- [x] 솝마디 결과 뷰 화면 전환
- [x] 부적 화면 전환
- [x] 부적 화면 데이터 바인딩
