### ISSUE TITLE
[Fix] 솝마디 결과뷰 컴포넌트 수정

### ISSUE THREAD

**Issue by dlwogus0128** [sopt-makers/SOPT-iOS#396]
## 📌  Issue

솝마디 결과뷰에서의 컴포넌트를 수정합니다.

- 콕찌르기 관련 컴포넌트 (ProfileImageView, KokButton) DSKit으로 옮기기
- ProfileImageView 버튼 터치 시 플그 프로필로 연결
- ProfileImageView Border 삭제

## 📝  To-do

- [x] 콕찌르기 관련 컴포넌트 (ProfileImageView, KokButton) DSKit으로 옮기기
- [x] ProfileImageView 버튼 터치 시 플그 프로필로 연결
- [x] ProfileImageView Border 삭제
