### ISSUE TITLE
[Fix] 글 작성 뷰 1차 QA

### ISSUE THREAD

**Issue by yangsubinn** [sopt-makers/SOPT-iOS#82]
## 📌  Issue

글 작성 뷰 1차 QA
<img width="1095" alt="스크린샷 2023-01-07 오후 8 13 44" src="https://user-images.githubusercontent.com/81167570/211147330-5a69e75d-cf1f-4dd8-8350-7105c4ba3d2d.png">

## 📝  To-do

- [x] 미션 작성일 날짜 텍스트 위치 수정
- [x] 글 수정시 텍스트뷰 상태 수정
- [x] 스탬프 등록시 백그라운드에서 이미지 상태 변하는게 보이는 이슈 확인
- [x] 글 수정시 하단 버튼 '수정 완료'로 변경
