### ISSUE TITLE
[Fix] 회원가입 및 비밀번호 변경 뷰 1차 QA

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-iOS#87]
## 📌  Issue

- 회원가입, 회원가입 완료 뷰, 비밀 번호 변경 뷰  1차 QA

## 📝  To-do

- [x] 회원 가입 완료 후 메인페이지로 화면 전환
- [x] 이메일 중복일 때 텍스트 안내
- [x] 닉네임, 이메일 텍스트 필드 변경 시 가입하기 버튼 비활성화
- [x] 비밀번호 변경뷰에서 비밀번호 텍스트 제거
- [ ] 회원가입의 비밀번호 입력 시 @ 특수문자 입력하면 다음 텍스트 필드로 넘어가는 문제 해결
